### ISSUE TITLE
Implement multiple voting strategies

### ISSUE THREAD

**Issue by bench1ps** [qandidate-labs/qandidate-toggle#12]
Right now, the `ToggleManager` replies positively to an active toggle request if at least one condition is met. But what if we need some more complex filters ? For example : the feature is active for users with a locale *en_GB* and a email address with *@test.com*.

I am aware that the voting process should remain simple, but would it be a good idea to implement different voting strategies ? These strategies could be similar to the ones found on the Symfony access decision manager : `AFFIRMATIVE`, `CONSENSUS` and `UNANIMOUS`.

**Comment by wjzijderveld** [comment]
Fixed with #13
