### ISSUE TITLE
More powerful expressions

### ISSUE THREAD

**Issue by webmozart** [qandidate-labs/qandidate-toggle#24]
Hi all :)

Great job on your project! Since you add some support for conditional expressions, you might be interested in the package [webmozart/expression](https://github.com/webmozart/expression). This package basically works in the same way as your operators, but has much more functionality already.

Cheers,
Bernhard

**Comment by asm89** [comment]
@webmozart Your package seems interesting, mostly because of the DSL in PHP itself. Most users of this package will use a data store to back their toggles, some I'm not sure what the immediate benefit would be?

**Comment by webmozart** [comment]
The immediate benefit is that you get many more logical expressions and operators out of the box compared to your own `Operator` implementations. For users of `ExpressionLanguage`, there's no change.
