### ISSUE TITLE
Example "from-yaml.php" has a bug / InMemoryCollectionSerializer requires a toggle's key to be its name

### ISSUE THREAD

**Issue by bertramakers** [qandidate-labs/qandidate-toggle#27]
The example at https://github.com/qandidate-labs/qandidate-toggle/blob/master/examples/from-yaml.php has a bug which causes all toggles to be considered as disabled. The $toggles->active(...) method first checks if the specific toggle actually exists, and the InMemoryCollection() does so by checking if a key with the name of the toggle exists in its internal array. This means that the yaml list of toggles should be an associative array with the names of the toggles as keys, as so:

    $yaml = <<<YML
    toggles:
      some-feature:
         name: some-feature
        conditions:
         - name: operator-condition
           key: user_id
           operator:
               name: greater-than
               value: 41
           status: conditionally-active
      some-feature-2:
        name: some-feature2
        conditions:
         - name: operator-condition
           key: user_id
           operator:
               name: greater-than
               value: 42
           status: conditionally-active
    YML;

Alternatively, you could change the InMemoryCollectionSerializer so it no longer requires the key of the toggle to be its name, but instead read the name from the "name" property. This is the current code which assumes the toggle's key to be its name (but in the example it would be an integer):

    /**
     * @param array $data
     * @return InMemoryCollection
     */
    public function deserialize(array $data)
    {
        $collection = new InMemoryCollection();
        $serializer = new ToggleSerializer(new OperatorConditionSerializer(new OperatorSerializer()));

        foreach ($data as $name => $serializedToggle) {
            $toggle = $serializer->deserialize($serializedToggle);
            $collection->set($name, $toggle);
        }

        return $collection;
    }

I would gladly fix the issue myself and provide a pull request, but I'm not sure what the intended behavior is. The main question is whether or not the array passed to InMemoryCollection::deserialize() is required to be an associative array or not. It should be fairly easy to allow a non-associative array to be passed without breaking backwards compatibility (as the name of the toggle should already be available in the toggle data itself), so maybe that's the better solution to prevent more confusion from new users in the future? On the other hand an associative array prevents duplicates from the start.

**Comment by asm89** [comment]
@bertramakers A pull request would be great. :+1: Not requiring the key of the array to be the name of the toggle sounds like a sane fix and I'm pretty certain it's a backwards compatible one indeed.

**Comment by bertramakers** [comment]
Great, I'll look into it and create a pull request soon.

**Comment by wjzijderveld** [comment]
Fixed in #34
