### ISSUE TITLE
EqualsTo operator in OperatorSerializer

### ISSUE THREAD

**Issue by dmolineus** [qandidate-labs/qandidate-toggle#28]
The EqualTo operator got renamed in e84227a8e05a61f667e5674fa3a34bbc22e6fc49. Unfortunately the `OperatorSerializer` still try to create the EqualsTo operation.

**Comment by grisha87** [comment]
This has been addressed in my PR #30

**Comment by asm89** [comment]
Fixed by @grisha87. Thanks again!
