### ISSUE TITLE
Why isn't ToggleCollection interface?

### ISSUE THREAD

**Issue by fmasa** [qandidate-labs/qandidate-toggle#29]
Hi,
I like your package, but I must aks:
Why is Qandidate\Toggle\ToggleCollection abstract class and not interface? There is no base code for Collections and it only makes custom inheritance more complicated.

Is there any reason for favoring asbtract class over interface?

**Comment by asm89** [comment]
No specific reason. It shouldn't be a problem when implementing a custom implementation of the collection? It favors composition over inheritance I guess.
